package com.microsoft.appcenter.crashes.model;
/* loaded from: classes3.dex */
public class TestCrashException extends RuntimeException {
    static final String CRASH_MESSAGE = "Test crash exception generated by SDK";

    public TestCrashException() {
        super(CRASH_MESSAGE);
    }
}
